[features]
seeds = false
skip-lint = false
[programs.localnet]
election = "4x29BQPwdRqbYWFNoT7YrN3SQfB9sYTFeBJejwsCqhYb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/bhaskarkh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
